    output_dir: "model_outputs"
    num_train_epochs: 1
    learning_rate: 2.0e-5
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    warmup_ratio: 0.1
    seed: 42
    data_seed: 42
    evaluation_strategy: "steps"
    eval_steps: 10
    logging_steps: 10
    dataloader_drop_last: True